- name: 检查指定用户{{ username }}是否存在
  shell: id {{ username }}
  register: usercheck_output
  ignore_errors: yes

- name: 显示指定用户{{ username }}是否存在
  debug:
    msg: "{{ usercheck_output.stdout }}"

- name: 检查指定用户{{ username }}是否配置sudo权限
  shell: grep ^{{ username }} /etc/sudoers
  register: usersudo_output
  ignore_errors: yes

    
- name: 显示指定用户{{ username }}是否配置sudo权限
  debug:
    msg: "{{ usersudo_output.stdout_lines }}"


