- name: system-auth配置口令锁定策略,连续登录失败3次锁定账号
  lineinfile:
    path: /etc/pam.d/system-auth
    regexp: '^auth\s*required\s*pam_faillock.so'
    line: 'auth        required      pam_faillock.so preauth audit deny=3 even_deny_root unlock_time=60'
    backup: yes
  ignore_errors: yes
- name: system-auth配置口令锁定策略,连续登录失败3次锁定账号
  lineinfile:
    path: /etc/pam.d/system-auth
    regexp: '^auth\s*\[default=die\]\s*pam_faillock.so'
    line: 'auth        [default=die] pam_faillock.so authfail audit deny=3 even_deny_root unlock_time=60'
    backup: yes
  ignore_errors: yes
- name: system-auth配置口令锁定策略,连续登录失败3次锁定账号
  lineinfile:
    path: /etc/pam.d/system-auth
    regexp: '^auth\s*sufficient\s*pam_faillock.so'
    line: 'auth        sufficient    pam_faillock.so authsucc audit deny=3 even_deny_root unlock_time=60'
    backup: yes
  ignore_errors: yes

- name: password-auth配置口令锁定策略,连续登录失败3次锁定账号
  lineinfile:
    path: /etc/pam.d/password-auth
    regexp: '^auth\s*required\s*pam_faillock.so'
    line: 'auth        required      pam_faillock.so preauth audit deny=3 even_deny_root unlock_time=60'
    backup: yes
  ignore_errors: yes
- name: password-auth配置口令锁定策略,连续登录失败3次锁定账号
  lineinfile:
    path: /etc/pam.d/password-auth
    regexp: '^auth\s*\[default=die\]\s*pam_faillock.so'
    line: 'auth        [default=die] pam_faillock.so authfail audit deny=3 even_deny_root unlock_time=60'
    backup: yes
  ignore_errors: yes
- name: password-auth配置口令锁定策略,连续登录失败3次锁定账号
  lineinfile:
    path: /etc/pam.d/password-auth
    regexp: '^auth\s*sufficient\s*pam_faillock.so'
    line: 'auth        sufficient    pam_faillock.so authsucc audit deny=3 even_deny_root unlock_time=60'
    backup: yes
  ignore_errors: yes

- import_tasks: check.yml