- name:  检查firewalld防火墙服务运行情况
  shell: systemctl status firewalld
  register: firewalld_output
  ignore_errors: yes
- name: 显示firewalld防火墙服务运行情况
  debug: 
    msg: "{{ firewalld_output.stdout_lines }}"
